### ISSUE TITLE
Master branch lacks videos

### ISSUE THREAD

**Issue by LeafyLappa** [ufoaiorg/ufoai#43]
I'm unable to run the game after compiling, intro won't play and the game just hangs after initial loading screen.
Doing make pk3 also tells me that the video files are missing, and there's no videos directory in /base.

make pk3:
```
zip warning: 0videos.pk3 not found or empty
zip warning: zip file empty
```

game output:
```
====== UFO Initialized ======
=============================
Switch grab input off
Could not load cinematic 'videos/intro'
Killed
```

**Comment by Greentaily** [comment]
Apparently the problem lies somewhere else. The game package from Linux Mint repos doesn't seem to have intro cinematic as well (does it even exist), but the game runs just fine.

**Comment by Greentaily** [comment]
Got the game running by copying config.cfg from 2.5 and changing cl_introshown to 0. There was no config file otherwise.

**Comment by DarkRainX** [comment]
The intro video was removed some time ago, of course, the game shouldn't crash because of that, will investigate.

**Comment by geever** [comment]
What I expect happened here, is that somehow your config.cfg & keys.cfg were empty, and keybindings and mouse clicks did not work, while were on the intro screen (as we said the intro video was removed).
