### ISSUE TITLE
put down object

### ISSUE THREAD

**Issue by DarthMoulByte** [ufoaiorg/ufoai#44]
al time in the same place make this, mor of 30 times i repeat the same process and obtained the same bug.

i put a grenade in this place, and apear a cube jaja :P sorry is funny but if you teach me how the source code is built, I just need to tell me what each file does and I can review it promptly and find an efficient solution for you to make the final decision if you agree to include the repair or not, and work once more on something that you consider appropriate

![ufo_2018-04-25_22-48-39](https://user-images.githubusercontent.com/24207840/39327154-ca13ea84-495c-11e8-881c-175d8f8e6d65.png)

**Comment by geever** [comment]
Case gone cold
