### ISSUE TITLE
Make tag for existing release

### ISSUE THREAD

**Issue by HumanG33k** [ufoaiorg/ufoai#46]
Can be cool to have tag for existing release.

**Comment by geever** [comment]
Our primary repository is on sourceforge.net. We do have release tags in that. Github is a backup repository of ours where we transfer commits from the master branch in case sourceforge has any trouble.

**Comment by HumanG33k** [comment]
You should add this fact somewhere we can see it here. 
In order to make people go in the right place.

**Comment by HumanG33k** [comment]
@geever  do you see my last message ?

**Comment by geever** [comment]
Our Website (and Wiki) makes it clear where the project and the sourcecode is:
https://ufoai.org/
https://ufoai.org/wiki/Getting_the_source

The error message you posted: What is it about? Are you contacting me about Sourceforge.net issues or what?

-geever

**Comment by HumanG33k** [comment]
Agree about the website, but people can come from here.

yes sry i was not really clear the error is from :
https://ufoai.org/bugs/ufoalieninvasion 
when i want create an account to make my bug/enhancement  report.

i don t know you manage it.

**Comment by geever** [comment]
I'm experimenting with self-hosting a Gitea, I could set it up to mirror SourceForge to my Gitea, and then my Gitea to Github. It is quite cool! This mirroring copied over the tags too.
