### ISSUE TITLE
Border glitch

### ISSUE THREAD

**Issue by HumanG33k** [ufoaiorg/ufoai#47]
Version 2.5
Debian testing 

I have some purple/pink border glitch on some screen. 
Last seen on hired scientists screen but not only on it.

**Comment by geever** [comment]
Could you attach some screenshots?
My guesses are a) missing texture from the debian package; b) videocard driver issue.

**Comment by geever** [comment]
Please also note that our bugtracker is on https://ufoai.org

**Comment by HumanG33k** [comment]
Ok i will use it in the future.
![Capture d’écran_2019-09-07_17-55-47](https://user-images.githubusercontent.com/1794193/64477204-dd53c680-d198-11e9-9c19-2f8d94245405.png)

**Comment by geever** [comment]
In the latest master (on SF) this whole UI is re-built.
