### ISSUE TITLE
2.6-dev Missing resolution option

### ISSUE THREAD

**Issue by FalcoGer** [ufoaiorg/ufoai#52]
I have a 1600x900 monitor. This option is not available in the game.

**Comment by geever** [comment]
We offer resolutions detected by the underlying SDL/SDL2 library. Still you can set arbitrary resolution by vid_width and vid_height console variables:

`ufo.exe +set vid_width 1600 +set vid_height 900`

We have feature-request ticket already for a "Custom" video mode option for the UI: https://ufoai.org/bugs/ufoalieninvasion/issues/5738

**Comment by geever** [comment]
With pre-set resolution we plan to stick SDL's available resolution detection, while still offering custom resolution options. (Today: via command line, later: via UI).
