### ISSUE TITLE
Reaction fire on aliens broken?

### ISSUE THREAD

**Issue by misiektw** [ufoaiorg/ufoai#59]
In current 2.6 master build aliens can come up, shoot you few times, hide, and when you engage them next turn, they still have full TU's for reaction fire (ie. two-three blasts from plasma rifle). 

This makes any weapon above 8TU almost useless to shoot, and only indirect fire is safe. Forget about unloading FA point blank, your soldier will be almost always dead before it goes off. And sniper shots are borderline suicidal.

I'm not sure if this is intended, that aliens should have almost twice the TU-s, but it was so frustrating that after few lost soldiers to pure bs I disabled it all together in base/ai/alien.lua. If someone has the same issue, you can change  ai.reactionfire("enable") to ai.reactionfire("disable"). 
Not perfect, because sometimes I expect RF, like from camping alien, but at least I can play now.

**Comment by geever** [comment]
Reaction Fire Reservation is taken from the current turn's TU, not the next turn's. Every Team starts their turn with full TU.
