### ISSUE TITLE
Antarctica Broken Savegame File BUG

### ISSUE THREAD

**Issue by whenhou** [ufoaiorg/ufoai#61]
Bug testet with 2.5 and 2.6:
The following will happen, if an UFO is landing or crashing at antarctica area in geoscape the save game file will become corroupted, if you save form that time on.

Using 2.5 and 2.6 at Windows 10.

**Comment by DarkRainX** [comment]
Do you have a save game showing this that you can attach?

**Comment by whenhou** [comment]
Maybe I can recreate a saveghame for sure, I will h

ave to wait until an ufo is landing or crashing again at antarktika.
________________________________

**Comment by geever** [comment]
I'm pretty sure this is the old 2.5 bug with the buggy German language file which results a corrupted XML. It has been fixed in git (both 2.5 and master branch), but we had no new releases since that. Unfortunately, corrupted saves have to be fixed manually.
