### ISSUE TITLE
Herakles is bulls*** :D (poor strategic design)

### ISSUE THREAD

**Issue by daniel-santos** [ufoaiorg/ufoai#63]
The Herakles dropship has a very poor design and it seems that it always lands with the opening facing the edge of the map, requiring most of the first turn trying to get your troops somewhere near where the battle is, making it unnecessarily difficult to save citizens.

When I look at troop troop carrier ships from the real world (e.g., WWII ships at Normandy) they landed with the opening to the enemy and tended to be wider so that troops could disembark more quickly.  I wouldn't dare say that the overall shape of the ship should be changed, but I would say that it *should* allow troops to depart more quickly, probably with additional exits on the sides like the Firebird, though they need not be as wide.

I haven't dug too deeply into this game yet, but I'm guessing that this is actually dictated by the models? And that this would be in the `models/aircraft/drop_herakles` directory in one of the ~~.pig/hog~~ .pk3 files?

I did Quake mods a long, *long*, ***LONG*** time ago, but I'm guessing I'll need to figure out those tools again in order to modify this and present a patch?

thanks

**Comment by geever** [comment]
Hello.

Saying something is bull** is not the nicest, nor the most efficient way to suggest a change.

For the alignment, you would need to change the maps via uforadiant, for opening other doors probably change the model as well. 

However, I don't see facing to the inside of a map a good idea, as it would expose your soldiers in the dropship more for long range shots, and don't like the extra doors idea either. We were thinking about giving options to start inside, or around the dropship, well both have advantages and disadvantages.

Please note that the latest source can be found on [SourceForge](https://sourceforge.net/p/ufoai/code/ci/master/tree/), and the original source files of (some of) the models in our [Datasource](https://ufoai.org/datasource/).

Happy tinkering for you!

-geever

**Comment by daniel-santos** [comment]
> Saying something is bull** is not the nicest, nor the most efficient way to suggest a change.

You're SO right! Maybe *I'm* full of full of bulls***? I was just frustrated because it was really hard to save any citizens on some mission. (It might have been country mansion.)

Thank you for the response and helpful information! Dropping a smoke grenade could solve that unless an enemy has view of everybody and can get a reaction shot if anybody tries to throw one. But I forgot about troop placement. Perhaps placing them much closer to the exit would solve the problem as well.
